/**
 * 24h2025
 * Contrat API des 24h du code 2025.   Version Participant.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NomRessource } from './nomRessource';

/**
 * Cout d'un batiment, en ressource.
 */
export interface BatimentRessource { 
    /**
     * Id technique de la ressource
     */
    idRessource: string;
    ressource: NomRessource;
    /**
     * quantite de ressource consommée/gagnée
     */
    quantite: number;
}