/**
 * 24h2025
 * Contrat API des 24h du code 2025.   Version Participant.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BatimentBonus } from './batimentBonus';
import { BatimentRessource } from './batimentRessource';
import { NomBatiment } from './nomBatiment';

export interface Batiment { 
    /**
     * Identifiant techique du batiment
     */
    id: string;
    /**
     * Information sur l'utilité du batiment
     */
    description: string;
    type: NomBatiment;
    /**
     * Temps (nombre d'action) nécessaire à la construction
     */
    tempsConstruction: number;
    /**
     * Les merveilles sont uniques, et ne peuvent être construites que par une seule équipes.
     */
    estUneMerveille: boolean;
    /**
     * Listes des biomes sur lesquelles le batiment peux être construit
     */
    contructibleSur: Array<string>;
    /**
     * Coûts en ressource du batiment par tour
     */
    coutParTour: Array<BatimentRessource>;
    /**
     * Coûts en ressource du batiment à la construction
     */
    coutConstruction: Array<BatimentRessource>;
    /**
     * Bonus en ressource du batiment à la construction
     */
    bonusConstruction?: Array<BatimentRessource>;
    /**
     * Bonus apportées par le bâtiment, par tour, ou lors d'une action
     */
    bonus?: Array<BatimentBonus>;
    /**
     * Informations supplémentaire ce qu'apporte le batiment
     */
    supplement?: Array<string>;
}