/**
 * 24h2025
 * Contrat API des 24h du code 2025.   Version Participant.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BatimentBonusDeclenchement } from './batimentBonusDeclenchement';

/**
 * Bonus apporté par un batiment
 */
export interface BatimentBonus { 
    /**
     * Id technique de la ressource
     */
    idRessource: string;
    /**
     * Nom de la ressource
     */
    ressource: string;
    /**
     * quantite de ressource gagnée
     */
    quantite: number;
    /**
     * A qui est ciblé le bonus
     */
    cibleBonus: string;
    declenchement: BatimentBonusDeclenchement;
}