/**
 * 24h2025
 * Contrat API des 24h du code 2025.   Version Participant.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Détail d'un biome
 */
export interface Biome { 
    /**
     * Identifiant technique du biome
     */
    identifiant: string;
    /**
     * Le nom du biome
     */
    nom: string;
    /**
     * Description du biome
     */
    description: string;
    /**
     * La liste des batiments qu'il est possible de construire sur ce biome
     */
    batimentsContructible: Array<string>;
}