/**
 * 24h2025
 * Contrat API des 24h du code 2025.   Version Participant.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Ressource } from './ressource';

/**
 * Information d'une ressource par rapport à une case
 */
export interface CaseRessources { 
    /**
     * quantite de ressource présente
     */
    quantite: number;
    ressource: Ressource;
}