/**
 * 24h2025
 * Contrat API des 24h du code 2025.   Version Participant.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Batiment } from './batiment';
import { Equipe } from './equipe';

/**
 * Information sur un batiment par rapport à une case
 */
export interface CaseBatiment { 
    /**
     * Nombre d'action de contruction restante avant la fin de la construction
     */
    progression: number;
    /**
     * Identifiant du batiment sur la case
     */
    identifiant: string;
    proprietaire: Equipe;
    detailBatiment: Batiment;
}