/**
 * 24h2025
 * Contrat API des 24h du code 2025.   Version Participant.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NomAction } from './nomAction';

export interface DemandeAction { 
    action: NomAction;
    /**
     * Pour les actions de récolte/contruction, la ressource/batiment à construire
     */
    reference?: string;
}