/**
 * 24h2025
 * Contrat API des 24h du code 2025.   Version Participant.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EquipeRessource } from './equipeRessource';
import { Villageois } from './villageois';

export interface Equipe { 
    /**
     * Identifiant technique de l'équipe
     */
    idEquipe: string;
    /**
     * Le super nom de l'équipe
     */
    nom: string;
    /**
     * Type de l'équipe
     */
    type: string;
    /**
     * Listes des villageois de l'équipe. N'est récupérée que si vous êtes propriétaire de l'équipe.
     */
    villageois: Array<Villageois>;
    /**
     * La liste des ressources possédées par l'équipe
     */
    ressources?: Array<EquipeRessource>;
}