/**
 * 24h2025
 * Contrat API des 24h du code 2025.   Version Participant.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Information concernant les erreurs d'API
 */
export interface ErreurAPI { 
    /**
     * Code erreur, sur deux chiffres. Indique des informations supplémentaire en plus du code retour HTTP.   * 1X - Erreur d'accès (droit) * 2X - Erreur de requête, paramètres invalides * 3X -- 8X - Erreur lié au jeu * 9X - Autre erreur, non prévu (bug chez nous :)) 
     */
    code: string;
    /**
     * Message détaillant l'erreur survenue
     */
    message: string;
    /**
     * Date à laquelle l'erreur est survenue
     */
    timestamp: Date;
}