/**
 * 24h2025
 * Contrat API des 24h du code 2025.   Version Participant.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Nom de l'action
 */
export type NomAction = 'DEPLACEMENT_DROITE' | 'DEPLACEMENT_GAUCHE' | 'DEPLACEMENT_HAUT' | 'DEPLACEMENT_BAS' | 'RECOLTER' | 'COMMENCER_CONSTRUCTION' | 'CONSTRUIRE' | 'RECYCLER_BATIMENT';

export const NomAction = {
    DEPLACEMENTDROITE: 'DEPLACEMENT_DROITE' as NomAction,
    DEPLACEMENTGAUCHE: 'DEPLACEMENT_GAUCHE' as NomAction,
    DEPLACEMENTHAUT: 'DEPLACEMENT_HAUT' as NomAction,
    DEPLACEMENTBAS: 'DEPLACEMENT_BAS' as NomAction,
    RECOLTER: 'RECOLTER' as NomAction,
    COMMENCERCONSTRUCTION: 'COMMENCER_CONSTRUCTION' as NomAction,
    CONSTRUIRE: 'CONSTRUIRE' as NomAction,
    RECYCLERBATIMENT: 'RECYCLER_BATIMENT' as NomAction
};