/**
 * 24h2025
 * Contrat API des 24h du code 2025.   Version Participant.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Les types de ressouces qui existes
 */
export type NomRessource = 'BOIS' | 'PIERRE' | 'FER' | 'CHARBON' | 'NOURRITURE' | 'ENERGIE' | 'POINT' | 'POLLUTION';

export const NomRessource = {
    BOIS: 'BOIS' as NomRessource,
    PIERRE: 'PIERRE' as NomRessource,
    FER: 'FER' as NomRessource,
    CHARBON: 'CHARBON' as NomRessource,
    NOURRITURE: 'NOURRITURE' as NomRessource,
    ENERGIE: 'ENERGIE' as NomRessource,
    POINT: 'POINT' as NomRessource,
    POLLUTION: 'POLLUTION' as NomRessource
};