/**
 * 24h2025
 * Contrat API des 24h du code 2025.   Version Participant.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NomRessource } from './nomRessource';
import { TypeRessource } from './typeRessource';

/**
 * Les ressources récoltables et produites par les équipes/villageois/batiments
 */
export interface Ressource { 
    /**
     * Identifiant technique de la ressource
     */
    idRessource: string;
    /**
     * Description de la ressource
     */
    description: string;
    nom: NomRessource;
    type: TypeRessource;
}