/**
 * 24h2025
 * Contrat API des 24h du code 2025.   Version Participant.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Type de l'action
 */
export type TypeAction = 'DEPLACEMENT' | 'RECOLTE' | 'CONSTRUCTION';

export const TypeAction = {
    DEPLACEMENT: 'DEPLACEMENT' as TypeAction,
    RECOLTE: 'RECOLTE' as TypeAction,
    CONSTRUCTION: 'CONSTRUCTION' as TypeAction
};